name: Run Data Preprocessing

# Trigger: Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  # Nama job
  run-preprocessing-split-scale:

    # Menentukan OS yang akan dipakai (Ubuntu versi terbaru)
    runs-on: ubuntu-latest
    # Memberikan izin agar action bisa menulis (commit) ke repository
    permissions:
      contents: write

    steps:
      # 1. Checkout (download) kode dari repository ke runner GitHub
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Sesuaikan jika versi Python berbeda

      # 3. Install semua library yang dibutuhkan oleh skrip .py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      # 4. Run skrip preprocessing
      #    Menggunakan path relatif untuk input dan output di dalam repo
      - name: Run preprocessing script (split, scale)
        run: python preprocessing/automate_Muhammad-Hafidz-Rizki.py --input loan_approval_raw.csv --output_folder loan_approval_preprocessing
        # Pastikan 'automate_Muhammad-Hafidz-Rizki.py' dan 'loan_approval_raw.csv' ada di root repository
        # atau sesuaikan path di atas jika lokasinya berbeda (misal: 'scripts/automate.py')

      # 5. Commit dan Push file baru (hasil preprocessing train & test) kembali ke repository
      - name: Commit processed train and test data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto: Update processed train and test data'
          # Menggunakan pola (*) untuk mencakup kedua file CSV di dalam folder
          file_pattern: 'loan_approval_preprocessing/loan_approval_*.csv'
          commit_user_name: 'hafidz34'
          commit_user_email: 'hafidzrizki443@gmail.com'